"""
Django settings for jwt_project project.

Generated by 'django-admin startproject' using Django 4.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
from firebase_admin import initialize_app


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-z3e9us&2u!9+9*1^sy2lm*r0t5dn&mkye!m!bvhl%znnvst)%k'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# AUTH_USER_MODEL = 'core.AppUser'

AUTH_USER_MODEL = 'core.AppUser'
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
    # 'chat',
    'import_export',
    'rest_framework_simplejwt',
    'rest_framework',
    # 'push_notifications'
    'fcm_django',
    'razorpayapp',
    'home',
    'django_extensions',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'jwt_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'jwt_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'jwt_database',
        'USER': 'admin',
        'PASSWORD': 'admin',
        'HOST': 'localhost',  # Or the host where your PostgreSQL server is running
        'PORT': '5432',       # The default PostgreSQL port is 5432
    }
}
# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
import os
import firebase_admin
from firebase_admin import credentials

RAZORPAY_API = ['RAZORPAY_API']
RAZORPAY_SECRET = ['RAZORPAY_SECRET']

# FIREBASE_ADMIN_CREDENTIAL = os.path.join(BASE_DIR, '/home/vinayak/Downloads/fcmbackend-40d8a-firebase-adminsdk-ghol9-709dd7c1f1.json')
# cred = credentials.Certificate(FIREBASE_ADMIN_CREDENTIAL)
# FIREBASE_APP = firebase_admin.initialize_app(cred)
# FIREBASE_APP = initialize_app()
# FIREBASE_CONFIG = {
#     "apiKey": "AAAAGFk-Sb4:APA91bGzPk0RrJNCoFIUtujRiDoAwhyg2mRxUsjlYF4K14Tkp8R0NFDKf1RRTCpnMah3GJLUO5D1AFCILKhN1OzeQsojFR3NIbaTq9tspKrXadB2nYveCax8_UNKiJDW_1ERIlZ_fW-j",
#     "authDomain": "YOUR_AUTH_DOMAIN",
#     "projectId": "fcmbackend-40d8a",
#     "storageBucket": "YOUR_STORAGE_BUCKET",
#     "messagingSenderId": "YOUR_MESSAGING_SENDER_ID",
#     "appId": "YOUR_APP_ID"
# } 
# FCM_DJANGO_SETTINGS = {
#     "APP_VERBOSE_NAME": "Your App Name",
#     "APP_NAME": "your_app_name",
#     "ONE_DEVICE_PER_USER": False,
# }


REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
    
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    )
}